<?php
namespace MagentoSync\Services;

use Illuminate\Database\Capsule\Manager as DB;
use MagentoSync\Helpers\Logger;

class UrlRewriteService {
    public static function process(int $productId, string $sku, string $name, ?string $customUrlKey = null): string {
        $urlKey = self::generateUrlKey($customUrlKey ?: $name);
        $fallbackUsed = false;

        // Check if URL key exists for a different product (conflict)
        $conflict = DB::table('url_rewrite')
            ->where('request_path', $urlKey)
            ->where('entity_type', 'product')
            ->where('entity_id', '!=', $productId)
            ->exists();

        if ($conflict) {
            $urlKey .= '-' . strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $sku));
            Logger::log("URL key conflict detected. Fallback used: {\$urlKey}");
            $fallbackUsed = true;
        }

        try {
            DB::table('url_rewrite')->updateOrInsert([
                'entity_type' => 'product',
                'entity_id' => $productId,
                'store_id' => 0,
                'request_path' => $urlKey
            ], [
                'target_path' => "catalog/product/view/id/$productId",
                'is_autogenerated' => 1,
                'redirect_type' => 0,
                'description' => null,
                'metadata' => null
            ]);
        } catch (\Throwable $e) {
            Logger::log("URL rewrite insert failed for product {\$productId}: " . $e->getMessage());
        }

        if ($fallbackUsed) {
            try {
                // Disable product by setting status in EAV table
                $statusAttribute = DB::table('eav_attribute')
                    ->where('attribute_code', 'status')
                    ->where('entity_type_id', 4)
                    ->first();

                if ($statusAttribute) {
                    DB::table('catalog_product_entity_int')->updateOrInsert([
                        'entity_id' => $productId,
                        'attribute_id' => $statusAttribute->attribute_id,
                        'store_id' => 0,
                    ], [
                        'value' => 2 // 2 = Disabled
                    ]);
                    Logger::log("Product {\$productId} status set to DISABLED due to URL key fallback.");
                } else {
                    Logger::log("Status attribute not found. Cannot disable product {\$productId}.");
                }
            } catch (\Throwable $e) {
                Logger::log("Failed to disable product {\$productId} after fallback: " . $e->getMessage());
            }
        }

        return $urlKey;
    }

    protected static function generateUrlKey(string $input): string {
        $slug = strtolower($input);
        // Replace any characters that are NOT alphanumeric, hyphen, or underscore with a hyphen
        $slug = preg_replace('/[^a-z0-9_-]+/i', '-', $slug);
        // Trim hyphens from the beginning and end of the string
        return trim($slug, '-');
    }
}
